# Generated by Django 2.0 on 2018-10-04 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181004_0611'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_test', to='users.Profile')),
            ],
            options={
                'ordering': ['skill_name'],
            },
        ),
        migrations.RemoveField(
            model_name='interest',
            name='description',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='description',
        ),
    ]
