# Generated by Django 2.0 on 2018-10-04 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181004_0647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skilltest',
            name='title',
        ),
    ]
