# Generated by Django 2.0 on 2018-09-21 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180921_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_type',
            field=models.IntegerField(choices=[(1, 'technical skill'), (2, 'soft skill')], default=1),
        ),
    ]
