# Generated by Django 2.1.1 on 2018-10-01 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_skill_skill_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu_name', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=30)),
                ('institute', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=80)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
            options={
                'ordering': ['edu_name'],
            },
        ),
    ]
