# Generated by Django 2.1.1 on 2018-10-01 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('company_name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_history', to='users.Profile')),
            ],
            options={
                'ordering': ['work_name'],
            },
        ),
        migrations.AlterField(
            model_name='education',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education', to='users.Profile'),
        ),
    ]
