# Generated by Django 2.1.1 on 2018-10-02 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_interest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChosenInterests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Interest')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='chosen_interests',
            field=models.ManyToManyField(to='users.Interest'),
        ),
        migrations.AddField(
            model_name='choseninterests',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
    ]
