# Generated by Django 2.0 on 2018-09-25 03:29

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript', models.FileField(blank=True, null=True, upload_to=users.models.scramble_uploaded_filename, verbose_name='Transcript')),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='data_created',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='transcript',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='users.Profile'),
        ),
    ]
