# Generated by Django 2.0 on 2018-09-25 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180925_0329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transcript',
            old_name='data_created',
            new_name='date_created',
        ),
    ]
